development: &development
 bucket: ENV["AWS_BUCKET"]
 access_key_id: ENV["AWS_ACCESS_KEY_ID"]
 secret_access_key: ENV["AWS_SECRET_ACCESS_KEY"]

test: 
 bucket: ENV["AWS_BUCKET"]
 access_key_id: ENV["AWS_ACCESS_KEY_ID"]
 secret_access_key: ENV["AWS_SECRET_ACCESS_KEY"]

production: &production
 bucket: andrewhouse
 access_key_id: ENV["AWS_ACCESS_KEY_ID"]
 secret_access_key: ENV["AWS_SECRET_ACCESS_KEY"]